export default {
  SIGNUP: 'AUTH::SIGNUP',
  SIGNUP_PENDING: 'AUTH::SIGNUP_PENDING',
  SIGNUP_FULFILLED: 'AUTH::SIGNUP_FULFILLED',
  SIGNUP_REJECTED: 'AUTH::SIGNUP_REJECTED',

  LOGOUT: 'AUTH::LOGOUT',
  LOGOUT_PENDING: 'AUTH::LOGOUT_PENDING',
  LOGOUT_FULFILLED: 'AUTH::LOGOUT_FULFILLED',
  LOGOUT_REJECTED: 'AUTH::LOGOUT_REJECTED',
};
